server:
  contextPath: /api
  port: 8008

spring:
  jpa:
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

token:
  secret: foobar123
  header: X-Auth-Token
#  Time in ms
#  864000000ms = 10 day
  expiration: 864000000

route:
  authentication:
    base: auth
    login: login
    refresh: refresh
    logout: logout
  seminar:
    base: seminars
    category: categories
  user:
    base: users
    all: all
    division: division
  booking:
    base: bookings
    grant: grant
    deny: deny
