server:
  contextPath: /api
  port: 8008

spring:
  jpa:
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

token:
  secret: foobar123
  header: X-Auth-Token
#  86400000 = 1 day
  expiration: 86400000
route:
  delete: delete
  authentication:
    base: auth
    login: login
    refresh: refresh
    logout: logout
  seminar:
    base: seminar
  user:
    base: user
