server:
# URL prefix
  contextPath: /api
  port: 8008

spring:
  jpa:
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

token:
# Used to sign the JWTs
  secret: foobar123
# Token header key
  header: X-Auth-Token
# Time in s
# 864000s  = 10 day
  expiration: 864000

# The variables used to build the URLs of all endpoints
route:
  authentication:
    base: auth
    login: login
    refresh: refresh
    logout: logout
  seminar:
    base: seminars
    current: current
    past: past
    category: categories
    bill: bill
  user:
    base: users
    all: all
    division: division
  booking:
    base: bookings
    grant: grant
    deny: deny
    seminar: seminar
